compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@wdio/browser-runner@*":
    dependencies:
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/local/plugin-workspaces-filter.js
  - path: .yarn/plugins/local/plugin-lifecycle-scripts.js
  - checksum: f6351bc3890cff235114eec78221a57b3adb164ee954eecd610a5fab5f2e7643fbdcfdaddc6689f2a177c7e3706f5b2333c7b47bffb848de6c051b5d97d48e0d
    path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://gist.githubusercontent.com/Mrtenz/06c33bfb39bb4c4a08bf2fff9404e763/raw/231163ae9d47f4de7e78fab2f966c4cadf052262/gistfile1.txt"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
